# Generated by Django 2.1 on 2019-05-27 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='标题', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='标题'),
        ),
    ]
